### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by a-poluhin** [kv-work/my-mvp-range-slider#5]
Имеет смысл разнести папки scale, bar и т. п. Например scale используется только во view можешь ее там и разместить. Сразу будет понятно что она используется во вью=) 
![image](https://user-images.githubusercontent.com/10168007/96613552-4c529700-1329-11eb-9d29-c96cadaca6e6.png)

**Comment by kv-work** [comment]
Всмысле перенести папки элементов View внутрь папки view?

**Comment by a-poluhin** [comment]
> Всмысле перенести папки элементов View внутрь папки view?

Ага
